name: Build TFLite Runtime Wheels on Debian Bookworm

on:
  workflow_dispatch:
  push:

env:
  TFLITE_VERSION: "2.17.1"

jobs:
  build:
    runs-on: ubuntu-latest
    # Run inside a Debian Bookworm container
    container:
      image: debian:bookworm

    strategy:
      matrix:
        python_version: ["3.11"]
        arch: ["x86_64"]

    steps:
    - name: Set up basic tools
      run: |
        apt-get update
        # Recommended to install locales if you see locale issues
        apt-get install -y locales
        # Choose your locale
        locale-gen en_US.UTF-8
        update-locale LANG=en_US.UTF-8

        # Core packages
        apt-get install -y \
          curl \
          git \
          gnupg \
          unzip \
          zip \
          wget \
          pkg-config \
          build-essential \
          lld

        # Optionally, install clang-17 from apt.llvm.org if not available by default
        wget -qO- https://apt.llvm.org/llvm.sh | bash -s -- 17
        ln -sf /usr/bin/clang-17 /usr/bin/clang
        ln -sf /usr/bin/clang++-17 /usr/bin/clang++

        echo "Clang version: $(clang --version)"

        # Install Python 3.11
        apt-get install -y python3.11 python3.11-dev python3.11-venv python3-pip

        # Set python3 as default (optional):
        # ln -sf /usr/bin/python3.11 /usr/bin/python3

        # Install Bazel from bazel.build (official instructions)
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > /usr/share/keyrings/bazel.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" > /etc/apt/sources.list.d/bazel.list
        apt-get update && apt-get install -y bazel

    - name: Checkout TensorFlow
      uses: actions/checkout@v4
      with:
        repository: tensorflow/tensorflow
        submodules: true
        fetch-depth: 0
        # Use the TFLite version environment variable
        ref: v${{ env.TFLITE_VERSION }}

    - name: Create and activate virtual environment
      run: |
        python3.11 -m venv /tmp/tflite_env
        source /tmp/tflite_env/bin/activate
        pip install --upgrade pip wheel setuptools
        # For TFLite, you usually need a matching NumPy version
        pip install numpy==1.26.4 auditwheel

    - name: Build TFLite Runtime Wheel
      run: |
        source /tmp/tflite_env/bin/activate
        export PYTHON_VERSION="${{ matrix.python_version }}"
        export NUMPY_VERSION="1.24.4"
        export TENSORFLOW_TARGET="${{ matrix.arch }}"
        export CC=clang
        export CXX=clang++

        # Enable XNNPACK & Flex
        CUSTOM_BAZEL_FLAGS+="--define=tflite_pip_with_xnnpack=true --define=tflite_pip_with_xnnpack_reshaping=true "
        CUSTOM_BAZEL_FLAGS+="--define=tflite_pip_with_flex=true "
        # If building for x86_64 with no AVX
        if [[ "${{ matrix.arch }}" == "x86_64" ]]; then
          CUSTOM_BAZEL_FLAGS+="--copt=-mno-avx --copt=-mno-avx2 --copt=-msse4.2 --copt=-msse4.1 "
        fi
        # Speed and size
        CUSTOM_BAZEL_FLAGS+="--define xnnpack_force_float_precision=fp16 "
        CUSTOM_BAZEL_FLAGS+="--define=no_tensorflow_py_deps=true --strip=always "
        CUSTOM_BAZEL_FLAGS+="--copt=-Wno-gnu-offsetof-extensions --features=-layering_check "

        export CUSTOM_BAZEL_FLAGS
        export TF_PYTHON_VERSION="${PYTHON_VERSION}"

        # Ensure a clean slate
        sed -i "/^bazel/i\bazel clean --expunge" tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh

        # Build the pip package using Bazel
        ./tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh

    - name: Prepare Wheel for Upload
      run: |
        mkdir -p /home/runner/work/wheels
        WHEEL_PATH=$(find tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist -name "*.whl" | head -n 1)
        if [[ -z "$WHEEL_PATH" ]]; then
          echo "Error: No wheel file found!"
          exit 1
        fi

        # For Python 3.11 => "cp311"
        echo "PY_TAG=$(echo ${{ matrix.python_version }} | sed 's/\\.//g')" >> $GITHUB_ENV

        NEW_WHEEL_PATH="/home/runner/work/wheels/tflite_runtime-${{ env.TFLITE_VERSION }}-${{ matrix.arch }}-cp${{ env.PY_TAG }}-cp${{ env.PY_TAG }}-linux_${{ matrix.arch }}.whl"
        mv "$WHEEL_PATH" "$NEW_WHEEL_PATH"
        echo "Wheel created: $NEW_WHEEL_PATH"

    - name: List Built Wheels
      run: ls -l /home/runner/work/wheels

    - name: Verify Wheel Architectures
      run: file /home/runner/work/wheels/*.whl

    - name: Upload Wheel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "tflite_runtime-${{ env.TFLITE_VERSION }}-${{ matrix.arch }}"
        path: /home/runner/work/wheels/*.whl

  release:
    runs-on: ubuntu-latest
    needs: build
    name: Create and Upload Release
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: wheels

      - name: List Downloaded Wheels
        run: find wheels

      - name: Authenticate GitHub CLI
        run: gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release (if not exists)
        run: |
          if gh release view ${{ env.TFLITE_VERSION }}2 -R "${{ github.repository }}" > /dev/null 2>&1; then
            echo "Release already exists. Skipping creation."
          else
            gh release create ${{ env.TFLITE_VERSION }}2 \
              -R "${{ github.repository }}" \
              --title "tflite_runtime ${{ env.TFLITE_VERSION }}" \
              --notes "Automated build for tflite_runtime ${{ env.TFLITE_VERSION }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Wheels to GitHub Release
        run: |
          gh release upload ${{ env.TFLITE_VERSION }}2 wheels/**/*.whl --clobber -R "${{ github.repository }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
